parameters:
  batch_size: 16
  img_size: 64
  generator:
    noise_dim: 100
    dropout_prob: 0.4
    learning_rate: "5e-5"
    batch_norm_momentum: 0.9
  discriminator:
    dropout_prob: 0.4
    learning_rate: "1e-5"
  rgb: false
train:
  epochs: 50
  save_interval: 25
data:
  directory: "C:/Users/Karl/Downloads/IconData/backup_data"