parameters:
  batch_size: 16
  img_size: 64
  generator:
    noise_dim: 100
    dropout_prob: 0.4
    learning_rate: "7e-6"
    batch_norm_momentum: 0.9
  discriminator:
    dropout_prob: 0.4
    learning_rate: "6e-6"
  rgb: true
train:
  epochs: 3500
  save_interval: 50
data:
  directory: "./out"